**NAME: NERELLA VENKATA RADHAKRISHNA**

**ID: 190031187**

**PRACTICAL-3**

In [2]:
import pandas as pd
import numpy as np

In [3]:
#1
#Importing Data From a CSV file
csvfile=pd.read_csv('housing.csv')
csvfile

       longitude  latitude  ...  median_house_value  ocean_proximity
0        -122.23     37.88  ...              452600         NEAR BAY
1        -122.22     37.86  ...              358500         NEAR BAY
2        -122.24     37.85  ...              352100         NEAR BAY
3        -122.25     37.85  ...              341300         NEAR BAY
4        -122.25     37.85  ...              342200         NEAR BAY
...          ...       ...  ...                 ...              ...
20635    -121.09     39.48  ...               78100           INLAND
20636    -121.21     39.49  ...               77100           INLAND
20637    -121.22     39.43  ...               92300           INLAND
20638    -121.32     39.43  ...               84700           INLAND
20639    -121.24     39.37  ...               89400           INLAND

[20640 rows x 10 columns]

In [4]:
#1
#Importing Data From a delimited text file (like TSV)
tsvfile=pd.read_table('housing.csv')
tsvfile

      longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0      -122.23,37.88,41,880,129,322,126,8.3252,452600...
1      -122.22,37.86,21,7099,1106,2401,1138,8.3014,35...
2      -122.24,37.85,52,1467,190,496,177,7.2574,35210...
3      -122.25,37.85,52,1274,235,558,219,5.6431,34130...
4      -122.25,37.85,52,1627,280,565,259,3.8462,34220...
...                                                  ...
20635  -121.09,39.48,25,1665,374,845,330,1.5603,78100...
20636  -121.21,39.49,18,697,150,356,114,2.5568,77100,...
20637  -121.22,39.43,17,2254,485,1007,433,1.7,92300,I...
20638  -121.32,39.43,18,1860,409,741,349,1.8672,84700...
20639  -121.24,39.37,16,2785,616,1387,530,2.3886,8940...

[20640 rows x 1 columns]

In [5]:
#1
#Importing Data From an Excel file
exfile=pd.read_excel(r'houseexcel.xlsx')
exfile

    total_rooms  total_bedrooms  ...  median_house_value  ocean_proximity
0           880             129  ...              452600         NEAR BAY
1          7099            1106  ...              358500         NEAR BAY
2          1467             190  ...              352100         NEAR BAY
3          1274             235  ...              341300         NEAR BAY
4          1627             280  ...              342200         NEAR BAY
5           919             213  ...              269700         NEAR BAY
6          2535             489  ...              299200         NEAR BAY
7          3104             687  ...              241400         NEAR BAY
8          2555             665  ...              226700         NEAR BAY
9          3549             707  ...              261100         NEAR BAY
10         2202             434  ...              281500         NEAR BAY
11         3503             752  ...              241800         NEAR BAY
12         2491             474  ...              213500         NEAR BAY
13          696             191  ...              191300         NEAR BAY
14         2643             626  ...              159200         NEAR BAY
15         1120             283  ...              140000         NEAR BAY
16         1966             347  ...              152500         NEAR BAY
17         1228             293  ...              155500         NEAR BAY
18         2239             455  ...              158700         NEAR BAY

[19 rows x 7 columns]

In [8]:
#1
#Importing Data  from a JSON formatted string
jsonfile=pd.read_json('housejson.json')
jsonfile

       longitude  latitude  ...  median_house_value  ocean_proximity
0        -122.23     37.88  ...              452600         NEAR BAY
1        -122.22     37.86  ...              358500         NEAR BAY
2        -122.24     37.85  ...              352100         NEAR BAY
3        -122.25     37.85  ...              341300         NEAR BAY
4        -122.25     37.85  ...              342200         NEAR BAY
...          ...       ...  ...                 ...              ...
20635    -121.09     39.48  ...               78100           INLAND
20636    -121.21     39.49  ...               77100           INLAND
20637    -121.22     39.43  ...               92300           INLAND
20638    -121.32     39.43  ...               84700           INLAND
20639    -121.24     39.37  ...               89400           INLAND

[20640 rows x 10 columns]

In [9]:
#2
#Viewing/Inspecting Data
csvfile.describe()

          longitude      latitude  ...  median_income  median_house_value
count  20640.000000  20640.000000  ...   20640.000000        20640.000000
mean    -119.569704     35.631861  ...       3.870671       206855.816909
std        2.003532      2.135952  ...       1.899822       115395.615874
min     -124.350000     32.540000  ...       0.499900        14999.000000
25%     -121.800000     33.930000  ...       2.563400       119600.000000
50%     -118.490000     34.260000  ...       3.534800       179700.000000
75%     -118.010000     37.710000  ...       4.743250       264725.000000
max     -114.310000     41.950000  ...      15.000100       500001.000000

[8 rows x 9 columns]

In [10]:
#2
#Viewing/Inspecting Data
csvfile.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  int64
 3   total_rooms         20640 non-null  int64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  int64
 6   households          20640 non-null  int64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  int64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(4), int64(5), object(1)
memory usage: 1.6+ MB

In [11]:
#2
#Viewing/Inspecting Data
csvfile.head()

   longitude  latitude  ...  median_house_value  ocean_proximity
0    -122.23     37.88  ...              452600         NEAR BAY
1    -122.22     37.86  ...              358500         NEAR BAY
2    -122.24     37.85  ...              352100         NEAR BAY
3    -122.25     37.85  ...              341300         NEAR BAY
4    -122.25     37.85  ...              342200         NEAR BAY

[5 rows x 10 columns]

In [12]:
#2
#Viewing/Inspecting Data
csvfile.tail()

       longitude  latitude  ...  median_house_value  ocean_proximity
20635    -121.09     39.48  ...               78100           INLAND
20636    -121.21     39.49  ...               77100           INLAND
20637    -121.22     39.43  ...               92300           INLAND
20638    -121.32     39.43  ...               84700           INLAND
20639    -121.24     39.37  ...               89400           INLAND

[5 rows x 10 columns]

In [13]:
#2
#Viewing/Inspecting Data
#Apply
csvfile.apply(pd.Series.value_counts)

            longitude  latitude  ...  median_house_value  ocean_proximity
-124.35           1.0       NaN  ...                 NaN              NaN
-124.3            2.0       NaN  ...                 NaN              NaN
-124.27           1.0       NaN  ...                 NaN              NaN
-124.26           1.0       NaN  ...                 NaN              NaN
-124.25           1.0       NaN  ...                 NaN              NaN
...               ...       ...  ...                 ...              ...
<1H OCEAN         NaN       NaN  ...                 NaN           9136.0
INLAND            NaN       NaN  ...                 NaN           6551.0
ISLAND            NaN       NaN  ...                 NaN              5.0
NEAR BAY          NaN       NaN  ...                 NaN           2290.0
NEAR OCEAN        NaN       NaN  ...                 NaN           2658.0

[24864 rows x 10 columns]

In [31]:
#3
#Glimpse
#slicing
csvfile.loc[1:8,'Longitude':'total_rooms']

   Longitude  Latitude  housing_median_age  total_rooms
1    -122.22     37.86                  21         7099
2    -122.24     37.85                  52         1467
3    -122.25     37.85                  52         1274
4    -122.25     37.85                  52         1627
5    -122.25     37.85                  52          919
6    -122.25     37.84                  52         2535
7    -122.25     37.84                  52         3104
8    -122.26     37.84                  42         2555

In [14]:
#3
#Data Cleaning
#unique
csvfile.households.unique()

array([ 126, 1138,  177, ..., 1767, 1832, 1818])

In [15]:
#3 
#Data Cleaning
#select (First Row)
csvfile.iloc[0,:]

longitude              -122.23
latitude                 37.88
housing_median_age          41
total_rooms                880
total_bedrooms             129
population                 322
households                 126
median_income           8.3252
median_house_value      452600
ocean_proximity       NEAR BAY
Name: 0, dtype: object

In [16]:
#3
#Data Cleaning
#select (By position)
csvfile.iloc[0,:5]

longitude            -122.23
latitude               37.88
housing_median_age        41
total_rooms              880
total_bedrooms           129
Name: 0, dtype: object

In [17]:
#3
#Data Cleaning
#select (By Index)
csvfile.loc[0]

longitude              -122.23
latitude                 37.88
housing_median_age          41
total_rooms                880
total_bedrooms             129
population                 322
households                 126
median_income           8.3252
median_house_value      452600
ocean_proximity       NEAR BAY
Name: 0, dtype: object

In [18]:
#3
#Data Cleaning
#list
csvfile.values.tolist()

[[-122.23, 37.88, 41, 880, 129.0, 322, 126, 8.3252, 452600, 'NEAR BAY'],
 [-122.22, 37.86, 21, 7099, 1106.0, 2401, 1138, 8.3014, 358500, 'NEAR BAY'],
 [-122.24, 37.85, 52, 1467, 190.0, 496, 177, 7.2574, 352100, 'NEAR BAY'],
 [-122.25, 37.85, 52, 1274, 235.0, 558, 219, 5.6431, 341300, 'NEAR BAY'],
 [-122.25, 37.85, 52, 1627, 280.0, 565, 259, 3.8462, 342200, 'NEAR BAY'],
 [-122.25, 37.85, 52, 919, 213.0, 413, 193, 4.0368, 269700, 'NEAR BAY'],
 [-122.25, 37.84, 52, 2535, 489.0, 1094, 514, 3.6591, 299200, 'NEAR BAY'],
 [-122.25, 37.84, 52, 3104, 687.0, 1157, 647, 3.12, 241400, 'NEAR BAY'],
 [-122.26, 37.84, 42, 2555, 665.0, 1206, 595, 2.0804, 226700, 'NEAR BAY'],
 [-122.25, 37.84, 52, 3549, 707.0, 1551, 714, 3.6912, 261100, 'NEAR BAY'],
 [-122.26, 37.85, 52, 2202, 434.0, 910, 402, 3.2031, 281500, 'NEAR BAY'],
 [-122.26, 37.85, 52, 3503, 752.0, 1504, 734, 3.2705, 241800, 'NEAR BAY'],
 [-122.26, 37.85, 52, 2491, 474.0, 1098, 468, 3.075, 213500, 'NEAR BAY'],
 [-122.26, 37.84, 52, 696, 191.0, 345, 174, 2.6736, 191300, 'NEAR BAY'],
 [-122.26, 37.85, 52, 2643, 626.0, 1212, 620, 1.9167, 159200, 'NEAR BAY'],
 [-122.26, 37.85, 50, 1120, 283.0, 697, 264, 2.125, 140000, 'NEAR BAY'],
 [-122.27, 37.85, 52, 1966, 347.0, 793, 331, 2.775, 152500, 'NEAR BAY'],
 [-122.27, 37.85, 52, 1228, 293.0, 648, 303, 2.1202, 155500, 'NEAR BAY'],
 [-122.26, 37.84, 50, 2239, 455.0, 990, 419, 1.9911, 158700, 'NEAR BAY'],
 [-122.27, 37.84, 52, 1503, 298.0, 690, 275, 2.6033, 162900, 'NEAR BAY'],
 [-122.27, 37.85, 40, 751, 184.0, 409, 166, 1.3578, 147500, 'NEAR BAY'],
 [-122.27, 37.85, 42, 1639, 367.0, 929, 366, 1.7135, 159800, 'NEAR BAY'],
 [-122.27, 37.84, 52, 2436, 541.0, 1015, 478, 1.725, 113900, 'NEAR BAY'],
 [-122.27, 37.84, 52, 1688, 337.0, 853, 325, 2.1806, 99700, 'NEAR BAY'],
 [-122.27, 37.84, 52, 2224, 437.0, 1006, 422, 2.6, 132600, 'NEAR BAY'],
 [-122.28, 37.85, 41, 535, 123.0, 317, 119, 2.4038, 107500, 'NEAR BAY'],
 [-122.28, 37.85, 49, 1130, 244.0, 607, 239, 2.4597, 93800, 'NEAR BAY'],
 [-122.28, 37.85, 52, 1898, 421.0, 1102, 397, 1.808, 105500, 'NEAR BAY'],
 [-122.28, 37.84, 50, 2082, 492.0, 1131, 473, 1.6424, 108900, 'NEAR BAY'],
 [-122.28, 37.84, 52, 729, 160.0, 395, 155, 1.6875, 132000, 'NEAR BAY'],
 [-122.28, 37.84, 49, 1916, 447.0, 863, 378, 1.9274, 122300, 'NEAR BAY'],
 [-122.28, 37.84, 52, 2153, 481.0, 1168, 441, 1.9615, 115200, 'NEAR BAY'],
 [-122.27, 37.84, 48, 1922, 409.0, 1026, 335, 1.7969, 110400, 'NEAR BAY'],
 [-122.27, 37.83, 49, 1655, 366.0, 754, 329, 1.375, 104900, 'NEAR BAY'],
 [-122.27, 37.83, 51, 2665, 574.0, 1258, 536, 2.7303, 109700, 'NEAR BAY'],
 [-122.27, 37.83, 49, 1215, 282.0, 570, 264, 1.4861, 97200, 'NEAR BAY'],
 [-122.27, 37.83, 48, 1798, 432.0, 987, 374, 1.0972, 104500, 'NEAR BAY'],
 [-122.28, 37.83, 52, 1511, 390.0, 901, 403, 1.4103, 103900, 'NEAR BAY'],
 [-122.26, 37.83, 52, 1470, 330.0, 689, 309, 3.48, 191400, 'NEAR BAY'],
 [-122.26, 37.83, 52, 2432, 715.0, 1377, 696, 2.5898, 176000, 'NEAR BAY'],
 [-122.26, 37.83, 52, 1665, 419.0, 946, 395, 2.0978, 155400, 'NEAR BAY'],
 [-122.26, 37.83, 51, 936, 311.0, 517, 249, 1.2852, 150000, 'NEAR BAY'],
 [-122.26, 37.84, 49, 713, 202.0, 462, 189, 1.025, 118800, 'NEAR BAY'],
 [-122.26, 37.84, 52, 950, 202.0, 467, 198, 3.9643, 188800, 'NEAR BAY'],
 [-122.26, 37.83, 52, 1443, 311.0, 660, 292, 3.0125, 184400, 'NEAR BAY'],
 [-122.26, 37.83, 52, 1656, 420.0, 718, 382, 2.6768, 182300, 'NEAR BAY'],
 [-122.26, 37.83, 50, 1125, 322.0, 616, 304, 2.026, 142500, 'NEAR BAY'],
 [-122.27, 37.82, 43, 1007, 312.0, 558, 253, 1.7348, 137500, 'NEAR BAY'],
 [-122.26, 37.82, 40, 624, 195.0, 423, 160, 0.9506, 187500, 'NEAR BAY'],
 [-122.27, 37.82, 40, 946, 375.0, 700, 352, 1.775, 112500, 'NEAR BAY'],
 [-122.27, 37.82, 21, 896, 453.0, 735, 438, 0.9218, 171900, 'NEAR BAY'],
 [-122.27, 37.82, 43, 1868, 456.0, 1061, 407, 1.5045, 93800, 'NEAR BAY'],
 [-122.27, 37.82, 41, 3221, 853.0, 1959, 720, 1.1108, 97500, 'NEAR BAY'],
 [-122.27, 37.82, 52, 1630, 456.0, 1162, 400, 1.2475, 104200, 'NEAR BAY'],
 [-122.28, 37.82, 52, 1170, 235.0, 701, 233, 1.6098, 87500, 'NEAR BAY'],
 [-122.28, 37.82, 52, 945, 243.0, 576, 220, 1.4113, 83100, 'NEAR BAY'],
 [-122.28, 37.82, 52, 1238, 288.0, 622, 259, 1.5057, 87500, 'NEAR BAY'],
 [-122.28, 37.82, 52, 1489, 335.0, 728, 244, 0.8172, 85300, 'NEAR BAY'],
 [-122.28, 37.82, 52, 1387, 341.0, 1074, 304, 1.2171, 80300, 'NEAR BAY'],
 [-122.29, 37.82, 2, 158, 43.0, 94, 57, 2.5625, 60000, 'NEAR BAY'],
 [-122.29, 37.83, 52, 1121, 211.0, 554, 187, 3.3929, 75700, 'NEAR BAY'],
 [-122.29, 37.82, 49, 135, 29.0, 86, 23, 6.1183, 75000, 'NEAR BAY'],
 [-122.29, 37.81, 50, 760, 190.0, 377, 122, 0.9011, 86100, 'NEAR BAY'],
 [-122.3,
  37.81,
  52,
  1224,
  237.0,
  521,
  159,
  1.1909999999999998,
  76100,
  'NEAR BAY'],
 [-122.3, 37.81, 48, 828, 182.0, 392, 133, 2.5938, 73500, 'NEAR BAY'],
 [-122.3, 37.81, 52, 1010, 209.0, 604, 187, 1.1667, 78400, 'NEAR BAY'],
 [-122.3, 37.81, 48, 1455, 354.0, 788, 332, 0.8056, 84400, 'NEAR BAY'],
 [-122.29, 37.8, 52, 1027, 244.0, 492, 147, 2.6094, 81300, 'NEAR BAY'],
 [-122.3, 37.81, 52, 572, 109.0, 274, 82, 1.8516, 85000, 'NEAR BAY'],
 [-122.29, 37.81, 46, 2801, 644.0, 1823, 611, 0.9802, 129200, 'NEAR BAY'],
 [-122.29, 37.81, 26, 768, 152.0, 392, 127, 1.7719, 82500, 'NEAR BAY'],
 [-122.29, 37.81, 46, 935, 297.0, 582, 277, 0.7286, 95200, 'NEAR BAY'],
 [-122.29, 37.81, 49, 844, 204.0, 560, 152, 1.75, 75000, 'NEAR BAY'],
 [-122.29, 37.81, 46, 12, 4.0, 18, 7, 0.4999, 67500, 'NEAR BAY'],
 [-122.29, 37.81, 20, 835, 161.0, 290, 133, 2.483, 137500, 'NEAR BAY'],
 [-122.28, 37.81, 17, 1237, 462.0, 762, 439, 0.9241, 177500, 'NEAR BAY'],
 [-122.28, 37.81, 36, 2914, 562.0, 1236, 509, 2.4464, 102100, 'NEAR BAY'],
 [-122.28, 37.81, 19, 1207, 243.0, 721, 207, 1.1111, 108300, 'NEAR BAY'],
 [-122.29, 37.81, 23, 1745, 374.0, 1054, 325, 0.8026, 112500, 'NEAR BAY'],
 [-122.28, 37.8, 38, 684, 176.0, 344, 155, 2.0114, 131300, 'NEAR BAY'],
 [-122.28, 37.81, 17, 924, 289.0, 609, 289, 1.5, 162500, 'NEAR BAY'],
 [-122.27, 37.81, 52, 210, 56.0, 183, 56, 1.1667, 112500, 'NEAR BAY'],
 [-122.28, 37.81, 52, 340, 97.0, 200, 87, 1.5208, 112500, 'NEAR BAY'],
 [-122.28, 37.81, 52, 386, 164.0, 346, 155, 0.8075, 137500, 'NEAR BAY'],
 [-122.28, 37.81, 35, 948, 184.0, 467, 169, 1.8088, 118800, 'NEAR BAY'],
 [-122.28, 37.81, 52, 773, 143.0, 377, 115, 2.4083, 98200, 'NEAR BAY'],
 [-122.27, 37.81, 40, 880, 451.0, 582, 380, 0.977, 118800, 'NEAR BAY'],
 [-122.27, 37.81, 10, 875, 348.0, 546, 330, 0.76, 162500, 'NEAR BAY'],
 [-122.27, 37.8, 10, 105, 42.0, 125, 39, 0.9722, 137500, 'NEAR BAY'],
 [-122.27, 37.8, 52, 249, 78.0, 396, 85, 1.2434, 500001, 'NEAR BAY'],
 [-122.27, 37.8, 16, 994, 392.0, 800, 362, 2.0938, 162500, 'NEAR BAY'],
 [-122.28, 37.8, 52, 215, 87.0, 904, 88, 0.8668, 137500, 'NEAR BAY'],
 [-122.28, 37.8, 52, 96, 31.0, 191, 34, 0.75, 162500, 'NEAR BAY'],
 [-122.27, 37.79, 27, 1055, 347.0, 718, 302, 2.6354, 187500, 'NEAR BAY'],
 [-122.27, 37.8, 39, 1715, 623.0, 1327, 467, 1.8477, 179200, 'NEAR BAY'],
 [-122.26, 37.8, 36, 5329, 2477.0, 3469, 2323, 2.0096, 130000, 'NEAR BAY'],
 [-122.26, 37.82, 31, 4596, 1331.0, 2048, 1180, 2.8345, 183800, 'NEAR BAY'],
 [-122.26, 37.81, 29, 335, 107.0, 202, 91, 2.0062, 125000, 'NEAR BAY'],
 [-122.26, 37.82, 22, 3682, 1270.0, 2024, 1250, 1.2185, 170000, 'NEAR BAY'],
 [-122.26, 37.82, 37, 3633, 1085.0, 1838, 980, 2.6104, 193100, 'NEAR BAY'],
 [-122.25, 37.81, 29, 4656, 1414.0, 2304, 1250, 2.4912, 257800, 'NEAR BAY'],
 [-122.25, 37.81, 28, 5806, 1603.0, 2563, 1497, 3.2177, 273400, 'NEAR BAY'],
 [-122.25, 37.81, 39, 854, 242.0, 389, 228, 3.125, 237500, 'NEAR BAY'],
 [-122.25, 37.81, 52, 2155, 701.0, 895, 613, 2.5795, 350000, 'NEAR BAY'],
 [-122.26, 37.81, 34, 5871, 1914.0, 2689, 1789, 2.8406, 335700, 'NEAR BAY'],
 [-122.24, 37.82, 52, 1509, 225.0, 674, 244, 4.9306, 313400, 'NEAR BAY'],
 [-122.24, 37.81, 52, 2026, 482.0, 709, 456, 3.2727, 268500, 'NEAR BAY'],
 [-122.25, 37.81, 52, 1758, 460.0, 686, 422, 3.1691, 259400, 'NEAR BAY'],
 [-122.24, 37.82, 52, 3481, 751.0, 1444, 718, 3.9, 275700, 'NEAR BAY'],
 [-122.25, 37.82, 28, 3337, 855.0, 1520, 802, 3.9063, 225000, 'NEAR BAY'],
 [-122.25, 37.82, 52, 1424, 289.0, 550, 253, 5.0917, 262500, 'NEAR BAY'],
 [-122.25, 37.82, 32, 3809, 1098.0, 1806, 1022, 2.6429, 218500, 'NEAR BAY'],
 [-122.25, 37.82, 26, 3959, 1196.0, 1749, 1217, 3.0233, 255000, 'NEAR BAY'],
 [-122.25, 37.83, 52, 2376, 559.0, 939, 519, 3.1484, 224100, 'NEAR BAY'],
 [-122.25, 37.83, 35, 1613, 428.0, 675, 422, 3.4722, 243100, 'NEAR BAY'],
 [-122.25, 37.83, 52, 1279, 287.0, 534, 291, 3.1429, 231600, 'NEAR BAY'],
 [-122.25, 37.83, 28, 5022, 1750.0, 2558, 1661, 2.4234, 218500, 'NEAR BAY'],
 [-122.25, 37.83, 52, 4190, 1105.0, 1786, 1037, 3.0897, 234100, 'NEAR BAY'],
 [-122.23, 37.84, 50, 2515, 399.0, 970, 373, 5.8596, 327600, 'NEAR BAY'],
 [-122.23, 37.84, 47, 3175, 454.0, 1098, 485, 5.2868, 347600, 'NEAR BAY'],
 [-122.24, 37.83, 41, 2576, 406.0, 794, 376, 5.956, 366100, 'NEAR BAY'],
 [-122.24, 37.85, 37, 334, 54.0, 98, 47, 4.9643, 335000, 'NEAR BAY'],
 [-122.23, 37.85, 52, 2800, 411.0, 1061, 403, 6.3434, 373600, 'NEAR BAY'],
 [-122.24, 37.84, 52, 3529, 574.0, 1177, 555, 5.1773, 389500, 'NEAR BAY'],
 [-122.24, 37.85, 52, 2612, 365.0, 901, 367, 7.2354, 391100, 'NEAR BAY'],
 [-122.22,
  37.85,
  28,
  5287,
  1048.0,
  2031,
  956,
  5.457000000000001,
  337300,
  'NEAR BAY'],
 [-122.22, 37.84, 50, 2935, 473.0, 1031, 479, 7.5, 295200, 'NEAR BAY'],
 [-122.21, 37.84, 44, 3424, 597.0, 1358, 597, 6.0194, 292300, 'NEAR BAY'],
 [-122.21, 37.83, 40, 4991, 674.0, 1616, 654, 7.5544, 411500, 'NEAR BAY'],
 [-122.2, 37.84, 30, 2211, 346.0, 844, 343, 6.0666, 311500, 'NEAR BAY'],
 [-122.21, 37.84, 34, 3038, 490.0, 1140, 496, 7.0548, 325900, 'NEAR BAY'],
 [-122.19, 37.84, 18, 1617, 210.0, 533, 194, 11.6017, 392600, 'NEAR BAY'],
 [-122.2, 37.84, 35, 2865, 460.0, 1072, 443, 7.4882, 319300, 'NEAR BAY'],
 [-122.21, 37.83, 34, 5065, 788.0, 1627, 766, 6.8976, 333300, 'NEAR BAY'],
 [-122.19, 37.83, 28, 1326, 184.0, 463, 190, 8.2049, 335200, 'NEAR BAY'],
 [-122.2, 37.83, 26, 1589, 223.0, 542, 211, 8.401, 351200, 'NEAR BAY'],
 [-122.19, 37.83, 29, 1791, 271.0, 661, 269, 6.8538, 368900, 'NEAR BAY'],
 [-122.19, 37.82, 32, 1835, 264.0, 635, 263, 8.317, 365900, 'NEAR BAY'],
 [-122.2, 37.82, 37, 1229, 181.0, 420, 176, 7.0175, 366700, 'NEAR BAY'],
 [-122.2, 37.82, 39, 3770, 534.0, 1265, 500, 6.3302, 362800, 'NEAR BAY'],
 [-122.18, 37.81, 30, 292, 38.0, 126, 52, 6.3624, 483300, 'NEAR BAY'],
 [-122.21, 37.82, 52, 2375, 333.0, 813, 350, 7.0549, 331400, 'NEAR BAY'],
 [-122.2, 37.81, 45, 2964, 436.0, 1067, 426, 6.7851, 323500, 'NEAR BAY'],
 [-122.21, 37.8, 50, 2833, 605.0, 1260, 552, 2.8929, 216700, 'NEAR BAY'],
 [-122.21, 37.8, 38, 2254, 535.0, 951, 487, 3.0812, 233100, 'NEAR BAY'],
 [-122.21, 37.81, 52, 1389, 212.0, 510, 224, 5.2402, 296400, 'NEAR BAY'],
 [-122.22, 37.81, 52, 1971, 335.0, 765, 308, 6.5217, 273700, 'NEAR BAY'],
 [-122.22, 37.8, 52, 2183, 465.0, 1129, 460, 3.2632, 227700, 'NEAR BAY'],
 [-122.22, 37.8, 52, 2286, 464.0, 1073, 441, 3.0298, 199600, 'NEAR BAY'],
 [-122.22, 37.8, 52, 2721, 541.0, 1185, 515, 4.5428, 239800, 'NEAR BAY'],
 [-122.22, 37.81, 52, 2024, 339.0, 756, 340, 4.072, 270100, 'NEAR BAY'],
 [-122.22, 37.81, 52, 2944, 536.0, 1034, 521, 5.3509, 302100, 'NEAR BAY'],
 [-122.23, 37.8, 52, 2033, 486.0, 787, 459, 3.1603, 269500, 'NEAR BAY'],
 [-122.23, 37.81, 52, 1433, 229.0, 612, 213, 4.7708, 314700, 'NEAR BAY'],
 [-122.22, 37.81, 52, 2927, 402.0, 1021, 380, 8.1564, 390100, 'NEAR BAY'],
 [-122.23, 37.81, 52, 2315, 292.0, 861, 258, 8.8793, 410300, 'NEAR BAY'],
 [-122.24, 37.81, 52, 2485, 313.0, 953, 327, 6.8591, 352400, 'NEAR BAY'],
 [-122.24, 37.81, 52, 1490, 238.0, 634, 256, 6.0302, 287300, 'NEAR BAY'],
 [-122.23,
  37.81,
  52,
  2814,
  365.0,
  878,
  352,
  7.507999999999999,
  348700,
  'NEAR BAY'],
 [-122.24, 37.81, 52, 2093, 550.0, 918, 483, 2.7477, 243800, 'NEAR BAY'],
 [-122.24, 37.8, 52, 888, 168.0, 360, 175, 2.1944, 211500, 'NEAR BAY'],
 [-122.25, 37.8, 52, 2087, 510.0, 1197, 488, 3.0149, 218400, 'NEAR BAY'],
 [-122.24, 37.81, 52, 2513, 502.0, 1048, 518, 3.675, 269900, 'NEAR BAY'],
 [-122.25, 37.81, 46, 3232, 835.0, 1373, 747, 3.225, 218800, 'NEAR BAY'],
 [-122.25, 37.8, 42, 4120, 1065.0, 1715, 1015, 2.9345, 225000, 'NEAR BAY'],
 [-122.25, 37.8, 43, 2364, 792.0, 1359, 722, 2.1429, 250000, 'NEAR BAY'],
 [-122.25, 37.8, 41, 1471, 469.0, 1062, 413, 1.6121, 171400, 'NEAR BAY'],
 [-122.25, 37.8, 29, 2468, 864.0, 1335, 773, 1.3929, 193800, 'NEAR BAY'],
 [-122.24, 37.79, 27, 1632, 492.0, 1171, 429, 2.3173, 125000, 'NEAR BAY'],
 [-122.25, 37.79, 45, 1786, 526.0, 1475, 460, 1.7772, 97500, 'NEAR BAY'],
 [-122.25, 37.79, 50, 629, 188.0, 742, 196, 2.6458, 125000, 'NEAR BAY'],
 [-122.25, 37.79, 52, 1339, 391.0, 1086, 363, 2.181, 138800, 'NEAR BAY'],
 [-122.25, 37.8, 36, 1678, 606.0, 1645, 543, 2.2303, 116700, 'NEAR BAY'],
 [-122.25, 37.8, 43, 2344, 647.0, 1710, 644, 1.6504, 151800, 'NEAR BAY'],
 [-122.24, 37.8, 52, 996, 228.0, 731, 228, 2.2697, 127000, 'NEAR BAY'],
 [-122.24, 37.8, 52, 1591, 373.0, 1118, 347, 2.1563, 128600, 'NEAR BAY'],
 [-122.24, 37.8, 52, 1586, 398.0, 1006, 335, 2.1348, 140600, 'NEAR BAY'],
 [-122.24, 37.8, 47, 2046, 588.0, 1213, 554, 2.6292, 182700, 'NEAR BAY'],
 [-122.23, 37.8, 52, 1192, 289.0, 772, 257, 2.3833, 146900, 'NEAR BAY'],
 [-122.24, 37.8, 52, 1803, 420.0, 1321, 401, 2.957, 122800, 'NEAR BAY'],
 [-122.24, 37.8, 49, 2838, 749.0, 1487, 677, 2.5238, 169300, 'NEAR BAY'],
 [-122.23, 37.8, 52, 783, 184.0, 488, 186, 1.9375, 126600, 'NEAR BAY'],
 [-122.23, 37.8, 51, 1590, 414.0, 949, 392, 1.9028, 127900, 'NEAR BAY'],
 [-122.23, 37.8, 50, 1746, 480.0, 1149, 415, 2.25, 123500, 'NEAR BAY'],
 [-122.23, 37.8, 52, 1252, 299.0, 844, 280, 2.3929, 111900, 'NEAR BAY'],
 [-122.23, 37.79, 43, 5963, 1344.0, 4367, 1231, 2.1917, 112800, 'NEAR BAY'],
 [-122.23, 37.79, 52, 1783, 395.0, 1659, 412, 2.9357, 107900, 'NEAR BAY'],
 [-122.23, 37.79, 30, 999, 264.0, 1011, 263, 1.8854, 137500, 'NEAR BAY'],
 [-122.24, 37.79, 39, 1469, 431.0, 1464, 389, 2.1638, 105500, 'NEAR BAY'],
 [-122.24, 37.79, 47, 1372, 395.0, 1237, 303, 2.125, 95500, 'NEAR BAY'],
 [-122.24, 37.79, 52, 674, 180.0, 647, 168, 3.375, 116100, 'NEAR BAY'],
 [-122.24, 37.79, 43, 1626, 376.0, 1284, 357, 2.2542, 112200, 'NEAR BAY'],
 [-122.25, 37.79, 51, 175, 43.0, 228, 55, 2.1, 75000, 'NEAR BAY'],
 [-122.25, 37.79, 39, 461, 129.0, 381, 123, 1.6, 112500, 'NEAR BAY'],
 [-122.25, 37.79, 52, 902, 237.0, 846, 227, 3.625, 125000, 'NEAR BAY'],
 [-122.26, 37.8, 20, 2373, 779.0, 1659, 676, 1.6929, 115000, 'NEAR BAY'],
 [-122.22, 37.77, 52, 391, 128.0, 520, 138, 1.6471, 95000, 'NEAR BAY'],
 [-122.22, 37.77, 52, 1137, 301.0, 866, 259, 2.59, 96400, 'NEAR BAY'],
 [-122.23, 37.77, 52, 769, 206.0, 612, 183, 2.57, 72000, 'NEAR BAY'],
 [-122.23, 37.78, 52, 472, 146.0, 415, 126, 2.6429, 71300, 'NEAR BAY'],
 [-122.23, 37.78, 52, 862, 215.0, 994, 213, 3.0257, 80800, 'NEAR BAY'],
 [-122.22, 37.78, 50, 1920, 530.0, 1525, 477, 1.4886, 128800, 'NEAR BAY'],
 [-122.23, 37.78, 43, 1420, 472.0, 1506, 438, 1.9338, 112500, 'NEAR BAY'],
 [-122.23, 37.78, 52, 986, 258.0, 1008, 255, 1.4844, 119400, 'NEAR BAY'],
 [-122.23, 37.78, 44, 2340, 825.0, 2813, 751, 1.6009, 118100, 'NEAR BAY'],
 [-122.23, 37.79, 48, 1696, 396.0, 1481, 343, 2.0375, 122500, 'NEAR BAY'],
 [-122.23, 37.79, 49, 1175, 217.0, 859, 219, 2.293, 106300, 'NEAR BAY'],
 [-122.22, 37.79, 37, 2343, 574.0, 1608, 523, 2.1494, 132500, 'NEAR BAY'],
 [-122.23, 37.79, 30, 610, 145.0, 425, 140, 1.6198, 122700, 'NEAR BAY'],
 [-122.23, 37.79, 40, 930, 199.0, 564, 184, 1.3281, 113300, 'NEAR BAY'],
 [-122.22, 37.79, 44, 1487, 314.0, 961, 272, 3.5156, 109500, 'NEAR BAY'],
 [-122.22, 37.79, 52, 3424, 690.0, 2273, 685, 3.9048, 164700, 'NEAR BAY'],
 [-122.21, 37.79, 52, 762, 190.0, 600, 195, 3.0893, 125000, 'NEAR BAY'],
 [-122.22, 37.79, 46, 2366, 575.0, 1647, 527, 2.6042, 124700, 'NEAR BAY'],
 [-122.22, 37.79, 49, 1826, 450.0, 1201, 424, 2.5, 136700, 'NEAR BAY'],
 [-122.22, 37.79, 38, 3049, 711.0, 2167, 659, 2.7969, 141700, 'NEAR BAY'],
 [-122.2, 37.79, 29, 1640, 376.0, 939, 340, 2.8321, 150000, 'NEAR BAY'],
 [-122.21, 37.79, 47, 1543, 307.0, 859, 292, 2.9583, 138800, 'NEAR BAY'],
 [-122.21, 37.79, 34, 2364, 557.0, 1517, 516, 2.8365, 139200, 'NEAR BAY'],
 [-122.21, 37.79, 35, 1745, 409.0, 1143, 386, 2.875, 143800, 'NEAR BAY'],
 [-122.21, 37.8, 39, 2003, 500.0, 1109, 464, 3.0682, 156500, 'NEAR BAY'],
 [-122.21, 37.8, 39, 2018, 447.0, 1221, 446, 3.0757, 151000, 'NEAR BAY'],
 [-122.2, 37.8, 43, 3045, 499.0, 1115, 455, 4.9559, 273000, 'NEAR BAY'],
 [-122.2, 37.8, 52, 1547, 293.0, 706, 268, 4.7721, 217100, 'NEAR BAY'],
 [-122.21, 37.8, 52, 3519, 711.0, 1883, 706, 3.4861, 187100, 'NEAR BAY'],
 [-122.2, 37.8, 41, 2070, 354.0, 804, 340, 5.1184, 239600, 'NEAR BAY'],
 [-122.21, 37.8, 48, 1321, 263.0, 506, 252, 4.0977, 229700, 'NEAR BAY'],
 [-122.19, 37.8, 48, 1694, 259.0, 610, 238, 4.744, 257300, 'NEAR BAY'],
 [-122.19, 37.8, 46, 1938, 341.0, 768, 332, 4.2727, 246900, 'NEAR BAY'],
 [-122.19, 37.79, 50, 968, 195.0, 462, 184, 2.9844, 179900, 'NEAR BAY'],
 [-122.2, 37.79, 40, 1060, 256.0, 667, 235, 4.1739, 169600, 'NEAR BAY'],
 [-122.2, 37.8, 46, 2041, 405.0, 1059, 399, 3.8487, 203300, 'NEAR BAY'],
 [-122.19, 37.8, 52, 1813, 271.0, 637, 277, 4.0114, 263400, 'NEAR BAY'],
 [-122.19, 37.79, 45, 2718, 451.0, 1106, 454, 4.6563, 231800, 'NEAR BAY'],
 [-122.19, 37.79, 28, 3144, 761.0, 1737, 669, 2.9297, 140500, 'NEAR BAY'],
 [-122.2, 37.79, 35, 1802, 459.0, 1009, 390, 2.3036, 126000, 'NEAR BAY'],
 [-122.2, 37.79, 49, 882, 195.0, 737, 210, 2.6667, 122000, 'NEAR BAY'],
 [-122.2,
  37.79,
  44,
  1621,
  452.0,
  1354,
  491,
  2.6189999999999998,
  134700,
  'NEAR BAY'],
 [-122.21, 37.79, 45, 2115, 533.0, 1530, 474, 2.4167, 139400, 'NEAR BAY'],
 [-122.2, 37.79, 45, 2021, 528.0, 1410, 480, 2.7788, 115400, 'NEAR BAY'],
 [-122.21, 37.78, 46, 2239, 508.0, 1390, 569, 2.7352, 137300, 'NEAR BAY'],
 [-122.21, 37.78, 52, 1477, 300.0, 1065, 269, 1.8472, 137000, 'NEAR BAY'],
 [-122.21, 37.78, 52, 1056, 224.0, 792, 245, 2.6583, 142600, 'NEAR BAY'],
 [-122.21, 37.78, 49, 898, 244.0, 779, 245, 3.0536, 137500, 'NEAR BAY'],
 [-122.22, 37.78, 44, 2968, 710.0, 2269, 610, 2.3906, 111700, 'NEAR BAY'],
 [-122.21, 37.78, 43, 1702, 460.0, 1227, 407, 1.7188, 126800, 'NEAR BAY'],
 [-122.21, 37.78, 47, 881, 248.0, 753, 241, 2.625, 111300, 'NEAR BAY'],
 [-122.22, 37.77, 40, 494, 114.0, 547, 135, 2.8015, 114800, 'NEAR BAY'],
 [-122.22, 37.78, 50, 1776, 473.0, 1807, 440, 1.7276, 102300, 'NEAR BAY'],
 [-122.22, 37.78, 44, 1678, 514.0, 1700, 495, 2.0801, 131900, 'NEAR BAY'],
 [-122.22, 37.78, 51, 1637, 463.0, 1543, 393, 2.489, 119100, 'NEAR BAY'],
 [-122.21, 37.76, 52, 1420, 314.0, 1085, 300, 1.7546, 80600, 'NEAR BAY'],
 [-122.21, 37.77, 52, 591, 173.0, 353, 137, 4.0904, 80600, 'NEAR BAY'],
 [-122.21, 37.77, 52, 745, 153.0, 473, 149, 2.6765, 88800, 'NEAR BAY'],
 [-122.2, 37.77, 49, 2272, 498.0, 1621, 483, 2.4338, 102400, 'NEAR BAY'],
 [-122.21, 37.77, 46, 1234, 375.0, 1183, 354, 2.3309, 98700, 'NEAR BAY'],
 [-122.21, 37.77, 43, 1017, 328.0, 836, 277, 2.2604, 100000, 'NEAR BAY'],
 [-122.19, 37.77, 42, 932, 254.0, 900, 263, 1.8039, 92300, 'NEAR BAY'],
 [-122.2, 37.77, 39, 2689, 597.0, 1888, 537, 2.2562, 94800, 'NEAR BAY'],
 [-122.2, 37.77, 41, 1547, 415.0, 1024, 341, 2.0562, 102000, 'NEAR BAY'],
 [-122.2, 37.78, 52, 2300, 443.0, 1225, 423, 3.5398, 158400, 'NEAR BAY'],
 [-122.2, 37.78, 39, 1752, 399.0, 1071, 376, 3.1167, 121600, 'NEAR BAY'],
 [-122.2, 37.78, 50, 1867, 403.0, 1128, 378, 2.5401, 129100, 'NEAR BAY'],
 [-122.2, 37.77, 43, 2430, 502.0, 1537, 484, 2.898, 121400, 'NEAR BAY'],
 [-122.21, 37.78, 44, 1729, 414.0, 1240, 393, 2.3125, 102800, 'NEAR BAY'],
 [-122.19, 37.78, 52, 1026, 180.0, 469, 168, 2.875, 160000, 'NEAR BAY'],
 [-122.19, 37.77, 52, 2170, 428.0, 1086, 425, 3.3715, 143900, 'NEAR BAY'],
 [-122.19, 37.77, 52, 2329, 445.0, 1144, 417, 3.5114, 151200, 'NEAR BAY'],
 [-122.19, 37.78, 52, 2492, 415.0, 1109, 375, 4.3125, 164400, 'NEAR BAY'],
 [-122.19, 37.78, 52, 2198, 397.0, 984, 369, 3.22, 156500, 'NEAR BAY'],

In [ ]:
#3
#Data Cleaning
#Selective renaming
csvfile.rename(columns={'housing_median_age':'Housing_Median_Age'},inplace=True)
csvfile

       longitude  latitude  ...  median_house_value  ocean_proximity
0        -122.23     37.88  ...              452600         NEAR BAY
1        -122.22     37.86  ...              358500         NEAR BAY
2        -122.24     37.85  ...              352100         NEAR BAY
3        -122.25     37.85  ...              341300         NEAR BAY
4        -122.25     37.85  ...              342200         NEAR BAY
...          ...       ...  ...                 ...              ...
20635    -121.09     39.48  ...               78100           INLAND
20636    -121.21     39.49  ...               77100           INLAND
20637    -121.22     39.43  ...               92300           INLAND
20638    -121.32     39.43  ...               84700           INLAND
20639    -121.24     39.37  ...               89400           INLAND

[20640 rows x 10 columns]

In [20]:
#3
#Data Cleaning
#Mass renaming of columns
csvfile.rename(columns={'latitude':'Latitude','longitude':'Longitude'},inplace=True)
csvfile

       Longitude  Latitude  ...  median_house_value  ocean_proximity
0        -122.23     37.88  ...              452600         NEAR BAY
1        -122.22     37.86  ...              358500         NEAR BAY
2        -122.24     37.85  ...              352100         NEAR BAY
3        -122.25     37.85  ...              341300         NEAR BAY
4        -122.25     37.85  ...              342200         NEAR BAY
...          ...       ...  ...                 ...              ...
20635    -121.09     39.48  ...               78100           INLAND
20636    -121.21     39.49  ...               77100           INLAND
20637    -121.22     39.43  ...               92300           INLAND
20638    -121.32     39.43  ...               84700           INLAND
20639    -121.24     39.37  ...               89400           INLAND

[20640 rows x 10 columns]

In [ ]:
#3
#Mass renaming of index
csvfile.rename(index=lambda x:x+1)

       longitude  latitude  ...  median_house_value  ocean_proximity
1        -122.23     37.88  ...              452600         NEAR BAY
2        -122.22     37.86  ...              358500         NEAR BAY
3        -122.24     37.85  ...              352100         NEAR BAY
4        -122.25     37.85  ...              341300         NEAR BAY
5        -122.25     37.85  ...              342200         NEAR BAY
...          ...       ...  ...                 ...              ...
20636    -121.09     39.48  ...               78100           INLAND
20637    -121.21     39.49  ...               77100           INLAND
20638    -121.22     39.43  ...               92300           INLAND
20639    -121.32     39.43  ...               84700           INLAND
20640    -121.24     39.37  ...               89400           INLAND

[20640 rows x 10 columns]

In [ ]:
#3
#Change the index
csvfile.rename(index={0:"x",1:"y",2:"z"})

       longitude  latitude  ...  median_house_value  ocean_proximity
x        -122.23     37.88  ...              452600         NEAR BAY
y        -122.22     37.86  ...              358500         NEAR BAY
z        -122.24     37.85  ...              352100         NEAR BAY
3        -122.25     37.85  ...              341300         NEAR BAY
4        -122.25     37.85  ...              342200         NEAR BAY
...          ...       ...  ...                 ...              ...
20635    -121.09     39.48  ...               78100           INLAND
20636    -121.21     39.49  ...               77100           INLAND
20637    -121.22     39.43  ...               92300           INLAND
20638    -121.32     39.43  ...               84700           INLAND
20639    -121.24     39.37  ...               89400           INLAND

[20640 rows x 10 columns]

In [ ]:
#4
#Filter
csvfile[csvfile['households']>150]

       longitude  latitude  ...  median_house_value  ocean_proximity
1        -122.22     37.86  ...              358500         NEAR BAY
2        -122.24     37.85  ...              352100         NEAR BAY
3        -122.25     37.85  ...              341300         NEAR BAY
4        -122.25     37.85  ...              342200         NEAR BAY
5        -122.25     37.85  ...              269700         NEAR BAY
...          ...       ...  ...                 ...              ...
20634    -121.56     39.27  ...              116800           INLAND
20635    -121.09     39.48  ...               78100           INLAND
20637    -121.22     39.43  ...               92300           INLAND
20638    -121.32     39.43  ...               84700           INLAND
20639    -121.24     39.37  ...               89400           INLAND

[19218 rows x 10 columns]

In [22]:
#4
#Sort (By a Column)
csvfile.sort_values('Longitude')

       Longitude  Latitude  ...  median_house_value  ocean_proximity
2655     -124.35     40.54  ...               94600       NEAR OCEAN
1861     -124.30     41.84  ...              103600       NEAR OCEAN
1851     -124.30     41.80  ...               85800       NEAR OCEAN
2631     -124.27     40.69  ...               79000       NEAR OCEAN
2653     -124.26     40.58  ...              111400       NEAR OCEAN
...          ...       ...  ...                 ...              ...
12450    -114.56     33.69  ...               85700           INLAND
2780     -114.55     32.80  ...               56100           INLAND
12447    -114.49     33.97  ...               87500           INLAND
13923    -114.47     34.40  ...               80100           INLAND
13924    -114.31     34.19  ...               66900           INLAND

[20640 rows x 10 columns]

In [23]:
#4
#Sort (By a Column) Descending Order
csvfile.sort_values('Longitude',ascending=False)

       Longitude  Latitude  ...  median_house_value  ocean_proximity
13924    -114.31     34.19  ...               66900           INLAND
13923    -114.47     34.40  ...               80100           INLAND
12447    -114.49     33.97  ...               87500           INLAND
2780     -114.55     32.80  ...               56100           INLAND
12450    -114.56     33.69  ...               85700           INLAND
...          ...       ...  ...                 ...              ...
2653     -124.26     40.58  ...              111400       NEAR OCEAN
2631     -124.27     40.69  ...               79000       NEAR OCEAN
1851     -124.30     41.80  ...               85800       NEAR OCEAN
1861     -124.30     41.84  ...              103600       NEAR OCEAN
2655     -124.35     40.54  ...               94600       NEAR OCEAN

[20640 rows x 10 columns]

In [25]:
#4
#GroupBy
csvfile.groupby("total_rooms")
csvfile

       Longitude  Latitude  ...  median_house_value  ocean_proximity
0        -122.23     37.88  ...              452600         NEAR BAY
1        -122.22     37.86  ...              358500         NEAR BAY
2        -122.24     37.85  ...              352100         NEAR BAY
3        -122.25     37.85  ...              341300         NEAR BAY
4        -122.25     37.85  ...              342200         NEAR BAY
...          ...       ...  ...                 ...              ...
20635    -121.09     39.48  ...               78100           INLAND
20636    -121.21     39.49  ...               77100           INLAND
20637    -121.22     39.43  ...               92300           INLAND
20638    -121.32     39.43  ...               84700           INLAND
20639    -121.24     39.37  ...               89400           INLAND

[20640 rows x 10 columns]

In [26]:
#4
#GroupBy
csvfile.groupby(["total_rooms","total_bedrooms"])
csvfile

       Longitude  Latitude  ...  median_house_value  ocean_proximity
0        -122.23     37.88  ...              452600         NEAR BAY
1        -122.22     37.86  ...              358500         NEAR BAY
2        -122.24     37.85  ...              352100         NEAR BAY
3        -122.25     37.85  ...              341300         NEAR BAY
4        -122.25     37.85  ...              342200         NEAR BAY
...          ...       ...  ...                 ...              ...
20635    -121.09     39.48  ...               78100           INLAND
20636    -121.21     39.49  ...               77100           INLAND
20637    -121.22     39.43  ...               92300           INLAND
20638    -121.32     39.43  ...               84700           INLAND
20639    -121.24     39.37  ...               89400           INLAND

[20640 rows x 10 columns]

In [27]:
#4
#pivot_table
csvfile.pivot_table(index="total_rooms",values=["total_bedrooms","population"],aggfunc=np.sum)

             population  total_bedrooms
total_rooms
2                     6             2.0
6                     8             2.0
8                    13             1.0
11                   24            11.0
12                   18             4.0
...                 ...             ...
30450              9419          5033.0
32054             15507          5290.0
32627             28566          6445.0
37937             16122          5471.0
39320             16305          6210.0

[5926 rows x 2 columns]

In [28]:
#5
#Perform Exploratory Data Analysis
csvfile.sample(8)

       Longitude  Latitude  ...  median_house_value  ocean_proximity
14324    -117.15     32.72  ...              137500       NEAR OCEAN
6227     -117.93     34.06  ...              202800        <1H OCEAN
12209    -117.02     33.60  ...              337200           INLAND
1158     -121.53     39.53  ...               91200           INLAND
4012     -118.60     34.16  ...              313100        <1H OCEAN
14842    -117.08     32.69  ...              117000       NEAR OCEAN
9911     -122.28     38.31  ...              166700         NEAR BAY
15162    -117.03     32.96  ...              182100        <1H OCEAN

[8 rows x 10 columns]